# Site Metadata
site_name: artart222 Portfolio/Blog
site_description: Portfolio and blog.
base_url: https://artart.dev
author: Artin Mobasher

asset_dirs:
  - ./source/assets

# Output Paths
source_directory: ./source
output_directory: ./output

# Template Engine
template_engine: django # or jinja2, etc.

plugins:
  - BlogIndexerPlugin
  - SpecialPagesPlugin
  - PageKeyWordExtractor
  - SitemapPlugin

# Program log levels:
# Debug = 10
# Info = 20
# Warning = 30
# Error = 40
# Critical = 50
log_level: 10

# Navigation (can also be in a separate data file)
navigation:
  - title: Home
    type: index
  - title: Blog
    type: blog-indexer
